In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
translations = np.load('translations.npy')
n = len(translations)

In [25]:
positions = [np.sum(translations[:i,:,0],axis=0) for i in range(n)]

In [26]:
distances = np.linalg.norm(positions)

[array([0., 0., 0.]),
 array([-0.15025175,  0.31482455,  0.9371819 ]),
 array([-0.24862459, -0.67763835,  1.0102584 ]),
 array([ 0.05865878, -0.55868731,  0.06610397]),
 array([-0.07473342, -0.78116317,  1.03187362]),
 array([-0.24985062, -1.03031679,  1.98437372]),
 array([-0.15733251, -1.47016661,  2.87766681]),
 array([ 0.20343847, -1.22258276,  1.97847465]),
 array([ 0.03649254, -1.44727398,  2.938497  ]),
 array([ 0.74391286, -2.15406709,  2.938497  ]),
 array([ 1.74391286, -2.15406709,  2.938497  ]),
 array([ 1.16656259, -1.57671682,  2.36114673]),
 array([ 0.63827951, -1.84081212,  3.16809819]),
 array([ 0.77791892, -1.72280583,  2.18495255]),
 array([ 0.80568664, -1.95474551,  1.21261879]),
 array([ 0.77404471, -2.60695924,  0.45524435]),
 array([ 0.22318178, -2.74010641,  1.27915082]),
 array([ 0.22318178, -3.74010641,  1.27915082]),
 array([-0.10388907, -3.55604463,  0.35224957]),
 array([-0.1720179 , -2.93271576, -0.42673668]),
 array([ 0.55721921, -2.77099914,  0.23813998])